POST http://localhost:8080/sign-in
Content-Type: application/json
Accept: application/json

{
  "email":"admin@gmail.com",
  "password":"password1"
}

###

POST http://localhost:8080/sign-up
Content-Type: application/json
Accept: application/json

{
  "email":"admin@gmail.com",
  "firstName":"admin",
  "lastName":"admin",
  "password":"password1"
}

<> 2020-02-14T085507.200.json
<> 2020-02-13T015248.200.json

###
//It'll be failed
GET  http://localhost:8080/greeting
Content-Type: application/json
Accept:  application/json

###