server:
  port: 8080

host:
  name: localhost

token:
  expiration: 45

key:
  privateKeyPath: keys/private_key.der
  publicKeyPath: keys/public_key.der

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}

  liquibase:
    change-log: classpath:db/changelog/master.xml

  security:
    oauth2:
      client:
        registration:
          github:
            clientId: eeacf48e0e78395ff9d2
            clientSecret: 2f153b8c518a841b2039cad37851111f80ed56ab