server:
  port: 8080

host:
  name: localhost

token:
  expiration: 45

key:
  privateKeyPath: keys/private_key.der
  publicKeyPath: keys/public_key.der

spring:
  datasource:
    url: ${DATASOURCE_URL}
    username: ${SQL_USERNAME}
    password: ${SQL_PASSWORD}

google:
  client-id: ${CLIENT_ID}
  client-secret: ${CLIENT_SECRET}

  liquibase:
    change-log: classpath:db/changelog/master.xml